//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public int ProductNumber { get; set; }
        public string ProductDescription { get; set; }
        public double PricePerItem { get; set; }
        public int AvailableQuantity { get; set; }
        public double CostPerItem { get; set; }
        public double ValueOfItem { get; set; }
        public string ProductName { get; set; }
    }
}
