//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        public string InventoryName { get; set; }
        public string InventoryEmail { get; set; }
        public string InventoryPhoneType { get; set; }
        public string InventoryPhoneNumber { get; set; }
        public int InventoryAge { get; set; }
        public string InventoryNotes { get; set; }
        public System.DateTime InventoryCreatedDate { get; set; }
    }
}
